let products = {
    data: [
        {
            id: 1,
            name: 'ORGANIC COTTON “OUR EARTH” T- SHIRT - GREEN',
            price: '750000',
            image: ['/earthday - products/products-imgs/our_earth_a.png', '/earthday - products/products-imgs/our_earth_b.png'],
            description: '',
            rate: 5.0,
        },
        {
            id: 2,
            name: 'REGIONAL PARK T- SHIRT - GREEN',
            price: '650000',
            image: ['/earthday - products/products-imgs/regional_park_a.png', '/earthday - products/products-imgs/regional_park_b.png'],
            description: '',
            rate: 4.0,
        },
        {
            id: 3,
            name: 'CLOUDY SUNSET LINEN PIJAMA - PINK',
            price: '1025000',
            image: ['/earthday - products/products-imgs/cloudy_sunset_a.png', '/earthday - products/products-imgs/cloudy_sunset_b.png'],
            description: '',
            rate: 3.5,
        },
        {
            id: 4,
            name: 'SAGE GARDEN SILK PIJAMA - SAGE',
            price: '1025000',
            image: ['/earthday - products/products-imgs/sage_garden_a.png', '/earthday - products/products-imgs/sage_garden_b.png'],
            description: '',
            rate: 4.5,
        },
        {
            id: 5,
            name: 'BAMBOO EVERYDAY SLIPDRESS - PINK',
            price: '950000',
            image: ['/earthday - products/products-imgs/bamboo_everyday_a.png', '/earthday - products/products-imgs/bamboo_everyday_b.png'],
            description: '',
            rate: 4.0,
        },
        {
            id: 6,
            name: 'ABSTRACT GRAPHIC ELEMENTS T - SHIRT - SAGE',
            price: '550000',
            image: ['/earthday - products/products-imgs/abstract_graphics_a.png', '/earthday - products/products-imgs/abstract_graphics_b.png'],
            description: '',
            rate: 4.5,
        },
        {
            id: 7,
            name: 'PEACEFUL SEA SHORTS - NAVY',
            price: '650000',
            image: ['/earthday - products/products-imgs/peaceful_sea_a.png', '/earthday - products/products-imgs/peaceful_sea_b.png'],
            description: '',
            rate: 4.2,
        },
        {
            id: 8,
            name: 'COTTON LINEN CINAMON SHIRT - BEIGE',
            price: '750000',
            image: ['/earthday - products/products-imgs/cinamon_a.png', '/earthday - products/products-imgs/cinamon_b.png'],
            description: '',
            rate: 4.4,
        },
        {
            id: 9,
            name: 'MAPLE SYRUP VELVET PANTS - ORANGE',
            price: '850000',
            image: ['/earthday - products/products-imgs/maple_syrup_a.png', '/earthday - products/products-imgs/maple_syrup_b.png'],
            description: '',
            rate: 4.5,
        },
        {
            id: 10,
            name: 'NIGHT ON SEINE PANTS - NAVY',
            price: '750000',
            image: ['/earthday - products/products-imgs/night_on_seine_a.png', '/earthday - products/products-imgs/night_on_seine_b.png'],
            description: '',
            rate: 4.7,
        },
        {
            id: 11,
            name: 'BIODEGRADABLE COTTON SWABS - CARE',
            price: '99000',
            image: ['/earthday - products/products-imgs/cotton_swab_a.png', '/earthday - products/products-imgs/cotton_swab_b.png'],
            description: '',
            rate: 4.6,
        },
        {
            id: 12,
            name: 'BAMBOO TOOTHBRUSH - CARE',
            price: '99000',
            image: ['/earthday - products/products-imgs/bamboo_toothbrush_a.png', '/earthday - products/products-imgs/bamboo_toothbrush_b.png'],
            description: '',
            rate: 5.0,
        },
        {
            id: 13,
            name: 'ECO - FRIENDLY HANDMADE SOAP - CARE',
            price: '150000',
            image: ['/earthday - products/products-imgs/handmade_soap_a.png', '/earthday - products/products-imgs/handmade_soap_b.png'],
            description: '',
            rate: 4.7,
        },
        {
            id: 14,
            name: 'SMELL OF NATURE SHAMPOO - CARE',
            price: '250000',
            image: ['/earthday - products/products-imgs/nature_shampoo_a.png', '/earthday - products/products-imgs/nature_shampoo_b.png'],
            description: '',
            rate: 4.3,
        },
        {
            id: 15,
            name: 'FLOURIDE FREE PEPPERMINT TOOTHPASTE - CARE',
            price: '250000',
            image: ['/earthday - products/products-imgs/peppermint_toothpaste_a.png', '/earthday - products/products-imgs/peppermint_toothpaste_b.png'],
            description: '',
            rate: 4.4,
        },
    ]
}
export default products